In [12]:
import numpy as np
a = np.full((4, 3, 2), 5)
# print(a)

b = np.ones((4, 3, 2), dtype=float)
# print(b)

c = np.zeros((4, 3, 2), dtype=str)
# print(c)

d = np.arange(9.0).reshape(3, 3)
# print(d[-1])

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr2[:-1] -= arr1[:-1]
# print(arr2)

e = np.array(range(9)).reshape(3, 3)
print(e)
print(np.sum(e, axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]


In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("PP_Force_anc_cropped.csv").values
np.savetxt("PP_Force_anc_cropped.txt", data, fmt="%s", delimiter=",")
